// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureVault.Infrastructure.Persistence;

#nullable disable

namespace SecureVault.Infrastructure.Migrations
{
    [DbContext(typeof(SecretVaultDbContext))]
    partial class SecretVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureVault.Infrastructure.Persistence.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("\"MessageId\" IS NOT NULL");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SecureVault.Infrastructure.Persistence.SecretEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("bytea");

                    b.Property<int>("ExpiryType")
                        .HasColumnType("integer");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPasswordProtected")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Nonce")
                        .HasMaxLength(12)
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordHashBase64")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("SaltForPassword")
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<string>("TokenHashBase64")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UtcCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UtcExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UtcRevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHashBase64")
                        .IsUnique();

                    b.ToTable("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
